### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by toddjames** [taeram/dizzy#1]
What is this project licensed under?

I am updating it for Python 3, removing the external dependencies, and changing the command-line options to allow for additional record types. I am considering forking it or I'm willing to send a pull request of the changes back into this project if those are welcome changes.

**Comment by taeram** [comment]
Hi @toddjames, apologies that it's taken this long to check my Issues tab! 

I've licensed the project under the MIT license in #2, and I would welcome any pull requests you have that'd improve / clean up the project. 

Thanks!
